n_examples: 3
moderation:
  name: vits
  audio_type: tts
  model_name_or_path: facebook/mms-tts-eng
  local: true
song:
  name: audiocraft
  audio_type: music
  model_name_or_path: facebook/musicgen-small
  local: false
